# Railway Configuration for LoomLite
# This tells Railway to use Docker instead of Nixpacks

[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "uvicorn backend.api:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/tree"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
